Django_WebBoard/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

Django_WebBoard/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작하는 페이지를 요청하면 이제 pybo/urls.py 파일의 매핑 정보를 읽어서 처리하라는 의미
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # '/'에 해당하는 path
]

Django_WebBoard/mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
        path('', views.index, name = 'index'),
        path('<int:question_id>/', views.detail, name = 'detail'),
        path('answer/create/<int:question_id>/', views.answer_create, name = 'answer_create'),
        path('question/create/', views.question_create, name='question_create'),
        # path('', views.NoticeListView.as_view(), name='question_list'),
        path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
        path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
        path('answer/modify/<int:answer_id>/', views.answer_modify, name = 'answer_modify'),
        path('answer/delete/<int:answer_id>/', views.answer_delete, name = 'answer_delete'),
    ]

Django_WebBoard/mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    subject = models.CharField(max_length = 200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null = True, blank = True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)  # 이 답변과 연결된 질문(Question)이 삭제될 경우 답변(Answer)도 함께 삭제된다는 의미이다.
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null = True, blank = True)

Django_WebBoard/mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

Django_WebBoard/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs = { 'class': 'form-control'}),
        #     'content': forms.Textarea(attrs = { 'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

Django_WebBoard/mysite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.

def signup(request):
    # 계정 생성
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = raw_password) # 사용자 인증
            login(request, user) # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

Django_WebBoard/mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.views.generic import ListView
# Create your views here.
# from django.http import HttpResponse

def index(request):
    # 목록 출력
    # 입력 파라미터
    page = request.GET.get('page', '1')

    # 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = { 'question_list': page_obj }
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # 내용 출력
    question = get_object_or_404(Question, pk = question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url = 'common:login')
def answer_create(request, question_id):
    # 답변 등록
    question = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)  # False: DB commit X (임시 저장)
            answer.author = request.user # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id = question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url = 'common:login')
def question_create(request):
    # 질문 등록
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # False: DB commit X (임시 저장)
            question.author = request.user # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form }
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url = 'common:login')
def question_modify(request, question_id):
    # 질문 수정 기능
    question = get_object_or_404(Question, pk = question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다')  # messeges 모듈을 이용해 오류 발생 시키기. (로그인 유저 != 글쓴이)
        return redirect('pybo:detail', question_id = question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance = question)
        if form.is_valid():
            question = form.save(commit = False)
            question.modify_date = timezone.now() # 수정일자 저장 (현재 일시로)
            question.save()
            return redirect('pybo:detail', question_id = question.id)
    else:
        form = QuestionForm(instance = question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url = 'common:login')
def question_delete(request, question_id):
    # 질문 삭제
    question = get_object_or_404(Question, pk = question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id = question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url = 'common:login')
def answer_modify(request, answer_id):
    # 답변 수정하기
    answer = get_object_or_404(Answer, pk = answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('pybo:detail', question_id = answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance = answer)
        if form.is_valid():
            answer = form.save(commit = False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id = answer.question.id)
    else:
        form = AnswerForm(instance = answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url = 'common:login')
def answer_delete(request, answer_id):
    # 답변 삭제
    answer = get_object_or_404(Answer, pk = answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id = answer.question.id)

Django_WebBoard/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1, shrink-to-fit=no"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>
    <!-- Pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- JQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!--JS Start-->
{% block script %}
{% endblock %}
<!--JS End-->
</body>
</html>

Django_WebBoard/mysite/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>Login</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
<!--        로그인 성공 후 이동하는 url-->
        <input type="hidden" name="text" value="{{ next }}"

        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}
</body>
</html>

Django_WebBoard/mysite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>

<div class="container my-3">
  <div class="row my-3">
    <div class="col-4">
      <h4>계정 생성하기</h4>
    </div>
      <div class="col-8 text-right">
          <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a></span>
      </div>
  </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">완료</button>
    </form>
</div>
{% endblock %}
</body>
</html>

Django_WebBoard/mysite/templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form_Errs</title>
</head>
<body>

{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {%for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

</body>
</html>

Django_WebBoard/mysite/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>navbar</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (logout)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
</body>
</html>

Django_WebBoard/mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">-->
{% block content %}
  <div class="container my-3">
      <!--사용자 오류 표시-->
      {% if messages %}
      <div class="alert alert-danger my-3" role="alert">
          {% for message in messages %}
            <strong>{{ message.tag }}</strong>
          <ul><li>{{ message.message }}</li></ul>
          {% endfor %}
      </div>
      {% endif %}
         <h2 class="border-bottom py-2"> {{ question.subject }} </h2>
      <div class="card my-3">
          <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">
                    {{ question.content }}
                </div>
              <div class="d-flex justify-content-end">
                  <div class="badge badge-light p-2 text-left">
                      <div class="mb-2"> {{ question.author.username }}</div>
                      <div>{{ question.create_date }}</div>
                      <div style="margin:10px"></div>
                  {% if question.modify_date %}
                      <div class="badge badge-light p2 text-left">
                          <div class="mb-2">modified at</div>
                         <div>{{ question.modify_date }}</div>
                      </div>
                  {% endif %}
                  </div>

              </div>
              {% if request.user == question.author %}
              <div class="my-3">
                  <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
              </div>
              {% endif %}
          </div>
      </div>
      <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
      {% for answer in question.answer_set.all %}
      <div class="card my-3">
          <div class="card-body">
              <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
              <div class="d-flex justify-content-end">
                  <div class="badge badge-light p-2 text-left">
                      <div class="mb-2"> {{ answer.author.username }}</div>
                      <div>{{ answer.create_date }}</div>   <!--만약 question.create_date 이면 답변 등록 시간 == 게시물 등록시간이 되므로 주의한다-->
                      <div style="margin:10px"></div>
                    {% if answer.modify_date %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                  </div>
              </div>
            {% if request.user == answer.author %}
              <div class="my-3">
                  <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
              </div>
            {% endif %}
          </div>
      </div>
      {% endfor %}
      <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
          {% endfor %}
      </div>
    {% endif %}
          <div class="form-group">
<!--          <textarea name="content" id="content" rows="10" class="form-control"></textarea> OLD code-->
              <textarea {% if not user.is_authenticated %}disabled{% endif%} name="content" class="form-control" rows="10"></textarea>
          </div>
        <input type = "submit" value = "답변등록" class="btn btn-primary">
      </form>
  </div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function() {
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}
</body>
</html>

Django_WebBoard/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문 등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- Error display -->
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
          {% endfor %}
      </div>
    {% endif %}
      <div class="form-group">
          <label for="subject">제목</label>
          <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
          <label for="content">내용</label>
          <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

</body>
</html>

Django_WebBoard/mysite/templates/pybo/question_from.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문 등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- Error display -->
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
          {% endfor %}
      </div>
    {% endif %}
      <div class="form-group">
          <label for="subject">제목</label>
          <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
          <label for="content">내용</label>
          <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

</body>
</html>

Django_WebBoard/mysite/templates/pybo/question_list.html
{% extends 'base.html' %}
<!-- 상단에 extends 구문이 있을 경우 load 구문은 그 하단에 위치-->
{% load pybo_filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
{% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <!--<td>{{ forloop.counter }}</td>-->
            <td>
                <!--번호 = 전체 건수 - 시작 index - 현재 index +1-->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-left">
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">[댓글: {{ question.answer_set.count }}]</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td> <!--글쓴이 추가-->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!--페이지 리스트-->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음 페이지-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징 처리 끝-->

    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}
</body>
</html>

templates/potato.html
<!DOCTYPE html>
<html>
    <head>
        <title>Job Search</title>
    </head>
        <body>
            <h1>Job Search</h1>
                <form action="/report" method="get"> 
                <!--html은 input의 정보를 받아 report로 보낸다.-->
                    <input placeholder='What job do you want?' required name="word"/>
                    <button>Search</button>
                </form>
        </body>
    </html>

templates/report.html
<!DOCTYPE html>
<html>
    <head>
        <title>Job Search</title>
        <style>
            section{
                display:grid;
                gap:20px;
                grid-template-columns: repeat(4,1fr);
                }
        </style>
    </head>
        <body>
            <h1>Search results</h1>
            <h3>Found {{resultsNum}} results for: {{searchingBy}}</h3>
            <a href="/export?word={{searchingBy}}">Export to CSV</a>
            <section>
                <h4>Title</h4>
                <h4>Company</h4>
                <h4>Location</h4>
                <h4>Link</h4>
                {% for job in jobs %}
                    <span>{{job.title}}</span>
                    <span>{{job.company}}</span>
                    <span>{{job.location}}</span>
                    <a href="{{job.apply_link}}" target="_blank">Apply</a>
                {% endfor %}
            </section>
                </form>
        </body>
    </html>